allprojects {
    version = '1.0.0-SNAPSHOT'

    repositories {
        mavenCentral()
        mavenLocal()
        maven { url "https://hub.spigotmc.org/nexus/content/groups/public/" }
        maven { url "https://libraries.minecraft.net/" }
        flatDir {
            dirs "${rootDir}/libs"
        }
    }
}