plugins {
    id 'java'
    id "com.github.johnrengelman.shadow" version "8.1.1"
    id 'net.minecrell.plugin-yml.bukkit' version '0.6.0'
}

group 'com.minecraft.generator'
version '1.5.7-SNAPSHOT'

compileJava.options.encoding = 'UTF-8'

repositories {
    mavenCentral()
    maven { url "https://hub.spigotmc.org/nexus/content/groups/public/" }
}

dependencies {

    compileOnly 'org.projectlombok:lombok:1.18.22'
    annotationProcessor 'org.projectlombok:lombok:1.18.22'

    compileOnly project(':core')

    compileOnly name: 'bukkit-server'
    compileOnly name: 'ViaVersion'
    compileOnly fileTree(dir: "${rootDir}/libs", include: ['*.jar'])
    testImplementation group: 'junit', name: 'junit', version: '4.12'
}

jar {
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}

bukkit {
    name = 'Generator'
    main = 'com.minecraft.generator.Generator'
    version = '1.5.7-' + gitVersion()
    website = 'www.ateumc.com'
    author = 'NesquikDeveloper'
    depend = ['TerrainControl']
    load = 'STARTUP'
    description = 'TerrainGen Bukkit Plugin [Terrain Control]'
}

static String gitVersion() {
    return 'git rev-parse --verify --short HEAD'.execute().getText().trim()
}

def shadowJarTask = tasks.getByName("shadowJar")

tasks.register("Ateu", Copy) {
    dependsOn shadowJarTask
    from shadowJarTask.outputs.files
    into "/home/NesquikDeveloper/AteuMC/updater"
}